name: Python Flask App

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "workflow" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies (in runner)
      run: |
        echo "Installing dependencies in runner..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        whoami

    - name: Run Flask app (in runner - for testing)
      run: |
        echo "Running Flask app in runner (for testing)..."
        python run.py &
        sleep 10
        curl http://192.168.23.50:5000
        PROCESS_ID=$(pgrep -f "python run.py")
        if [ -n "$PROCESS_ID" ]; then
          echo "Flask app process is running (PID: $PROCESS_ID)"
        else
          echo "Flask app process is not running"
          exit 1
        fi
        pkill -f run.py

    - name: Stop existing Flask process on server
      run: |
        echo "Stopping existing Flask process on server (if any)..."
        kill -9 $(pgrep -f "python3 /home/kelompok2/backend3/run.py") || true
        sleep 5 # Beri waktu sebentar untuk proses benar-benar berhenti

    - name: Adjust directory permissions
      run: |
        echo "Adjusting permissions for /home/kelompok2/backend3/..."
        ls -ld /home/kelompok2/backend3/
        chown -R kelompok2:kelompok2 /home/kelompok2/backend3/
        chmod -R 755 /home/kelompok2/backend3/

    - name: Deploy to production directory
      run: |
        echo "Deploying to production directory..."
        rm -rf /home/kelompok2/backend3/*
        sleep 5
        cp -r . /home/kelompok2/backend3/

    - name: Install dependencies (on server)
      run: |
        echo "Installing dependencies on server..."
        python3 -m venv /home/kelompok2/backend3/venv
        /home/kelompok2/backend3/venv/bin/pip install -r /home/kelompok2/backend3/requirements.txt

    - name: Start Flask app using nohup (on server)
      run: |
        source /home/kelompok2/backend3/venv/bin/activate
        echo "Starting Flask app on server..."
        nohup /home/kelompok2/backend3/venv/bin/python /home/kelompok2/backend3/run.py > /home/kelompok2/backend3/flask.log 2>&1 &
        curl http://192.168.23.50:5000
        echo "Flask app started in the background on /home/kelompok2/backend3/"

   

    - name: Show Flask log (optional)
      if: failure()
      run: |
        echo "--- Flask Log (last 50 lines from server) ---"
        tail -n 50 /home/kelompok2/backend3/flask.log || true
