name: Python Flask App

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "workflow" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout source code
      run: whoami
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies (in runner)
      run: |
        echo "Installing dependencies in runner..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask app (in runner - for testing)
      run: |
        echo "Running Flask app in runner (for testing)..."
        python run.py &
        sleep 10
        PROCESS_ID=$(pgrep -f "python run.py")
        if [ -n "$PROCESS_ID" ]; then
          echo "Flask app process is running (PID: $PROCESS_ID)"
        else
          echo "Flask app process is not running"
          exit 1
        fi
        pkill -f run.py
    - name: Deploy to production directory
      run: |
        echo "Deploying to production directory..."
       
        echo "Remove success"
        sudo mkdir -p /var/www/backend/
        sudo cp -r . /var/www/backend/

    - name: Install dependencies (on server)
      run: |
        echo "Installing dependencies on server..."
        sudo python3 -m venv /var/www/backend/venv
        sudo /var/www/backend/venv/bin/pip install -r /var/www/backend/requirements.txt

    - name: Stop existing Flask process (if any)
      run: |
        echo "Stopping existing Flask process on server (if any)..."
        sudo pkill -f "python3 /var/www/backend/run.py" || true

    - name: Start Flask app using nohup (on server)
      run: |
        echo "Starting Flask app on server..."
        sudo nohup /var/www/backend/venv/bin/python3 /var/www/backend/run.py > /var/www/backend/flask.log 2>&1 &
        echo "Flask app started in the background on /var/www/backend/"

    - name: Wait and check if Flask app is running (on server)
      run: |
        echo "Checking if Flask app
